### PR TITLE
Colors, sweet colors

### PR DESCRIPTION
**Pull request by Chris-V**
(aka code highlight)

I uploaded the result on the staging http://doc-staging-gwtp.appspot.com/

### CODE REVIEW

**Comment by christiangoudreau** [comment]
LGTM, what are the language supported by jygments?

**Comment by Chris-V** [comment]
I decided to go with jython + pygments instead: http://pygments.org/languages/

**Comment by meriouma** [comment]
Should we see the highlights on the staging? Or only the added classes?

**Comment by meriouma** [comment]
Nevermind, was a browser cache issue I think

**Comment by meriouma** [comment]
LGTM, looks way better!

**Comment by olafleur** [comment]
Really nice!

**Pull request merged**
