### PR TITLE
ADEV-71 - added support link

### PR DESCRIPTION
**Pull request by Pacane**
@jasonlemay @LarryMatte need to change the icon, the current one is GSSS'

### CODE REVIEW

**Comment by spg** [comment]
LGTM

**Comment by christiangoudreau** [comment]
Once the icon is changed, LGTM

**Comment by christiangoudreau** [comment]
@manolo New pimped documentation for gQuery!

@spg is this published automagically? 

@Pacane If yes, the link targe the old website?

**Comment by spg** [comment]
@christiangoudreau yes, new versions are deployed when commits are detected in master branch

**Comment by meriouma** [comment]
Not from TeamCity though, did you setup something?

**Comment by meriouma** [comment]
Ah, on the private one!

**Comment by meriouma** [comment]
@christiangoudreau This PR is not for the gquery doc, look at #78

**Comment by christiangoudreau** [comment]
I probably messed my tabs :D

Would be nice to have a little bit more space between "support" and the products

**Comment by spg** [comment]
@christiangoudreau have you created an issue in Jira for "a little bit more space between "support" and the products" ?

**Pull request merged**
