### PR TITLE
ADEV-98 - Removed unrecognized characters from License page

### PR DESCRIPTION
**Pull request by Pacane**

### CODE REVIEW

**Comment by Chris-V** [comment]
mmh, I added the unbreakable spaces to force the the markdown parser to put more spacing between the list elements. Can you check locally that it's still the case? Alternatively we could have jason or larry do something more css like

**Comment by Pacane** [comment]
Yeah would probably be best to let jason or larry handle this. And yes locally it was still doing it.

**Comment by meriouma** [comment]
+1 for css

**Comment by Chris-V** [comment]
LGTM

**Pull request merged**
